### PR TITLE
Fix/#2347 w payment query error

### LINKED ISSUE #2347: WPayment has error in query
===========> WPayment.dynInit: SELECT a.C_BP_BankAccount_ID, NVL(b.Name, ' ')||'_'||NVL(a.AccountNo, ' ') AS Acct FROM C_BP_BankAccount a LEFT OUTER JOIN C_Bank b ON (a.C_Bank_ID=b.C_Bank_ID) WHERE C_BPartner_ID=?AND a.IsActive='Y' AND a.IsACH='Y' [31]
org.postgresql.util.PSQLException: ERROR: column reference "c_bpartner_id" is ambiguous
  Position: 178; State=42702; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:76)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:100)
	at com.sun.proxy.$Proxy2.executeQuery(Unknown Source)
	at org.adempiere.webui.apps.form.WPayment.dynInit(WPayment.java:754)
	at org.adempiere.webui.apps.form.WPayment.<init>(WPayment.java:143)

### PR DESCRIPTION
**Pull request by mckayERP**
Fixes #2347.

See closed pull request #2348 for comments.

This was originally a one character change but there is so much duplicated code between VPayment and WPayment that it was a good opportunity to consolidate it.  I've stripped all but the bare essentials of the UI elements from both and created a common controller to manage the data.  Its pretty rough and doesn't behave as well as other dialogs but it is much better than what was there.

Along the way, I removed the connection to any previous payments.  Each time the payment dialog is run, it will create a new payment.  This allows a mix of cash and credit card, for example.   The amount shown in the dialog will be the outstanding amount.  When this hits zero, no further payment can be taken, but the user can enter another number.   If there is an invoice and it is paid, then no payment will be allowed.

I also changed the cash to use the bank.  I had to make some changes to MBankStatement and MPayment to make this work.  Cash payments will automatically be added to the correct Cash Closing document.  This is a great improvement as the payments are posted and the accounting is correct.

Online processes should work if these are set up.  I don't have a way of testing these but its the same process as the payment document.

Also error messages - I tried to use the special characters for the spanish but you'll have to check my (or google's) translations.  I added some error logging in MPayment as the log error stack is hard to work with.

I've added documentation on the dialog here:  https://adempiere.gitbook.io/docs/introduction/getting-started/dialogs-and-forms/payment-dialog.

### CODE REVIEW

**Comment by yamelsenih** [comment]
Hi @mckayERP it is a great change. Nicee

Please, have you a Step by Step for it?

I am trying to replicate it for Swing UI but I don't see changes.

beste regard

**Comment by mckayERP** [comment]
See VPayment.java.  That is the only change in Swing.  There is little
change to its appearance.

Mike

**Comment by mckayERP** [comment]
For step by step, see the document link.

File: base/src/org/compiere/model/MBankStatement.java [hunk 1]
```diff
@@ -712,4 +712,37 @@ public boolean isComplete()
...
 	
+	/**
+	 * 	Get BankStatement (CashJournal) for Bank Account and date
+	 *	@param ctx context
+	 *	@param C_BankAccount_ID cashbook
+	 *	@param dateAcct date
+	 *	@param trxName transaction
+	 *	@return The Bank Statement (Cash Journal)
+	 */
+	public static MBankStatement get (Properties ctx, int C_BankAccount_ID,
```
Comment (yamelsenih) [inline base/src/org/compiere/model/MBankStatement.java]: What is the reason for add this method?
If it is for create a bank statement automatically then already exists a static method for handle it:
<pre>
static public MBankStatementLine addPayment(MPayment payment)
</pre>

File: migration/391lts-392lts/04450_2347_FixWVPaymentReduceDupCode.xml [hunk 2]
```diff
@@ -0,0 +1,426 @@
...
+      </PO>
+    </Step>
+    <Step SeqNo="50" StepType="AD">
+      <PO AD_Table_ID="119" Action="I" Record_ID="0" Table="AD_Message_Trl">
+        <Data AD_Column_ID="342" Column="MsgText">Diario de Caja</Data>
+        <Data AD_Column_ID="344" Column="IsTranslated">true</Data>
+        <Data AD_Column_ID="609" Column="Created">2019-03-02 07:22:17.195</Data>
+        <Data AD_Column_ID="611" Column="Updated">2019-03-02 07:22:17.195</Data>
+        <Data AD_Column_ID="608" Column="IsActive">true</Data>
+        <Data AD_Column_ID="343" Column="MsgTip">Seleccione la definici&oacute;n de Diario de Caja a utilizar. Cualquier pago en efectivo creado se agregar&aacute; a un documento de Cierre de Caja del Diario de Caja seleccionado.</Data>
```
Comment (yamelsenih) [inline migration/391lts-392lts/04450_2347_FixWVPaymentReduceDupCode.xml]: Please fix it
<pre>
[Fatal Error] 04450_2347_FixWVPaymentReduceDupCode.xml:65:80: The entity "oacute" was referenced, but not declared.
org.xml.sax.SAXParseException; systemId: file:/opt/Development/workspace/adempierePullRequest/migration/391lts-392lts/04450_2347_FixWVPaymentReduceDupCode.xml; lineNumber: 65; columnNumber: 80; The entity "oacute" was referenced, but not declared.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:133)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:175)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:128)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.apps.ProcessCtl.startProcess(ProcessCtl.java:623)
	at org.compiere.apps.ProcessCtl.run(ProcessCtl.java:372)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by yamelsenih** [comment]
Hi @mckayERP I have some comments for it

**Comment by yamelsenih** [comment]
This is a great change and is nice to have fixed source code

**Comment by mckayERP** [comment]
That import worked just fine for me.

The accents in the Mexican translations are a real pain.  Is there not an easier way to add Mexican translations?

In this case, the oacute reference is for an accented "o".  How are you adding the accent characters?  Am I missing something with the xml file format - different encoding perhaps?

Mike

File: base/src/org/compiere/model/MBankStatement.java (hunk 1 above)
Comment (mckayERP) [reply base/src/org/compiere/model/MBankStatement.java]: Your right.  I didn't see that.  I'll make the correction.

**Comment by yamelsenih** [comment]
Let me change it for you

File: base/src/org/compiere/model/MBankStatement.java (hunk 1 above)
Comment (mckayERP) [reply base/src/org/compiere/model/MBankStatement.java]: Looking closer, I did use the static method in MPayment - new line 1887.  I think this method should have been deleted.  Again, I'll make the change and update the pull request.

**Comment by mckayERP** [comment]
Thanks!

**Comment by yamelsenih** [comment]
Please replace your SML for it
[04450_2347_FixWVPaymentReduceDupCode.tar.gz](https://github.com/adempiere/adempiere/files/3036726/04450_2347_FixWVPaymentReduceDupCode.tar.gz)

**Comment by yamelsenih** [comment]
> Please replace your SML for it
> [04450_2347_FixWVPaymentReduceDupCode.tar.gz](https://github.com/adempiere/adempiere/files/3036726/04450_2347_FixWVPaymentReduceDupCode.tar.gz)

Please review and replace your XML for it, note that is zipped as tar.gz

Best regard

**Comment by mckayERP** [comment]
OK.  Tomorrow.

**Comment by yamelsenih** [comment]
> OK. Tomorrow.

No problem, just replace tomorrow and I will to merge with special characters
