### PR TITLE
Close Order does not update Total Lines Amount and total amount

### LINKED ISSUE #3810: Close Order does not update Total Lines Amount and total amount
## Bug report

When a Sales Order is Closed and it has a line with Delivered Quantity less than the Ordered Quantity, the line is updated, correcting the Ordered Quantity but it doesn't update the header of the order with the NEW  Total Lines Amount.

<br class="Apple-interchange-newline">

#### Screenshot or Gif

https://user-images.githubusercontent.com/31936815/165549155-89acb05e-3a68-4ea8-93ae-1621f4ab3aa7.mp4

#### Expected behavior
It should update the Total Lines Amount, the Grand Total and the Tax Order

### PR DESCRIPTION
**Pull request by nsarlabos**
Fixes #3810

### CODE REVIEW

File: base/src/org/compiere/model/MOrder.java [hunk 1]
```diff
@@ -2187,6 +2187,12 @@ public boolean closeIt()
 			return false;
 		}
 
+		if (!calculateTaxTotal())
+		{
+			m_processMsg = "Error calculating tax";
```
Comment (e-Evolution) [inline base/src/org/compiere/model/MOrder.java:2192]: @nsarlabos Could you create messages in the dictionary so that the response to the user is multi-language?

`m_processMsg = "@ErrorCalculatingTax@";`

File: base/src/org/compiere/model/MOrder.java [hunk 2]
```diff
@@ -2243,6 +2249,12 @@ public String reopenIt() {
 			return "Failed to update reservations";
```
Comment (e-Evolution) [inline base/src/org/compiere/model/MOrder.java:2249]: @nsarlabos Could you create messages in the dictionary so that the response to the user is multi-language?

`m_processMsg = "@FailedToUpdateReservations@";`

File: base/src/org/compiere/model/MOrder.java [hunk 3]
```diff
@@ -2243,6 +2249,12 @@ public String reopenIt() {
...
 		}
 
+		if (!calculateTaxTotal())
+		{
+			m_processMsg = "Error calculating tax";
```
Comment (e-Evolution) [inline base/src/org/compiere/model/MOrder.java:2254]: @nsarlabos Could you create messages in the dictionary so that the response to the user is multi-language?

m_processMsg = "@ErrorCalculatingTax@";

File: base/src/org/compiere/model/MOrder.java [hunk 4]
```diff
@@ -2243,6 +2249,12 @@ public String reopenIt() {
...
+			return "Error calculating tax";
```
Comment (e-Evolution) [inline base/src/org/compiere/model/MOrder.java:2255]: here you should return m_processMsg;  vs same text

**Review by e-Evolution — CHANGES_REQUESTED** [review]
@nsarlabos Could you create error messages in the dictionary so that the response to the user is multi-language?

391 / 5.000
Resultados de traducción
The change seems correct to me, it is only better to do it multi-language.

1.- Enables the generation of Dictionary Maintenance and Migration Log Script
2.- Create the error messages by placing the word between @@ as a key, type of message Error and the message text of the error message
3.- Generates the XML for the changes in the dictionary.
4.- Send the changes in this pull request

**Comment by nsarlabos** [comment]
Hi @e-Evolution I have made the requested changes

**Comment by e-Evolution** [comment]
@nsarlabos Thank you to accept the suggestion
