### PR TITLE
Fixed multiples errors for ZK User Interface Improvement 

### LINKED ISSUE #3973: Date changes format in records as you change Mono and Grid
## Bug report
in a window with more than 40 records, in the last records the date changes it format showing MM/dd/yyyy when it should be dd/MM/yyyy.

The strange behaivor is that when you change the record form Grid to Mono, the date format changes and you see it ok.

#### Steps to reproduce

image

https://user-images.githubusercontent.com/31936815/185419581-484a918e-a935-4215-a3af-a11f7b0d364b.mp4

#### Other relevant information
- Your OS:
- Java version:
- ADempiere version: Develop
- Browser [e.g. chrome, safari] Chrome
- Browser Version [e.g. 22]
- DB Provider:
- DB version:

### LINKED ISSUE #4021: [Bug Report] Replace obsolete library cglib.jar not compatible with JDK 11 or >
## Bug report
- Replace obsolete library cglib.jar not compatible with JDK 11 or >
- The library cglib.jar launch --illegal-access=warn to enable warnings of further illegal reflective access operations

#### Expected behavior
The library should have support for JDK 11

#### Other relevant information
- Your OS: macOS
- Java version: 11
- ADempiere version: 3.9.4 nightly 
- Browser safari
- DB Provider: PG
- DB version: 15

#### Additional context
Replace by https://bytebuddy.net  with byte-buddy-1.12.19.jar compatible with JDK 11 o >

### LINKED ISSUE #4022: [Bug Report] Grid mode navigation has strange behavior
## Bug report
Grid mode navigation has strange behavior
- Error when switching the single and multi-mode row, The first problem is the single mode not how some content although multi-row row 1 is selected 
- Another problem is that when I select a row from a multi-row view, the status bar row does not change.

#### Steps to reproduce & Screenshot or Gif

1.- Open the Window Account Fact Balance :

image

2.- Switch to a single row:

image

The first problem is the single mode not how some content although multi-row row 1 is selected 

if switch again to multi-row mode then an empty error is added:

image

problem is that when I select a row from a multi-row view, the status bar row does not change.

image

The status bar show 1/105 when I selected another row

#### Expected behavior
When switching between single-line and multi-line modes the display should show the same information for the selected record in either mode.

When a row is selected in multi-row mode the status bar should update with the chosen record

#### Other relevant information
- Your OS: macOS
- Java version: 11
- ADempiere version: 3.9.4 nightly build
- Browser safari
- DB Provider: PG
- DB version: 15

#### Additional context
- Navigation between pages does not work correctly

### LINKED ISSUE #4023: [Bug Report] Quick Entry not working when the icon is pushed
## Bug report
[Bug Report] Quick Entry not working when the icon is pushed, never dialog to Quick Entry is shown

#### Steps to reproduce
1.- Login with System Administrator 
2.- Search into the Window, Tab & Field the Business Partner definition
3.- Setting the Quick Entry for fields Search Key, Name, Name 2, Description, Tax Id, Tax Group, and Business Partner Group
4.- Logout and Login with Garden Admin role 
5.- Open Business Partner Window 
6.- Push the Quick Entry icon button 
7.- Select the All record

#### Screenshot or Gif
image

#### Expected behavior
When the  Push the Quick Entry icon button the Quick Entry Dialog should be shown.

Here is shown as work apply the patch
image

#### Other relevant information
- Your OS: macOS
- Java version: 11
- ADempiere version: 3.9.4 nightly build 
- Browser safari
- DB Provider: PG
- DB version: 15

#### Additional context
The bug was introduced in PR #3371

### PR DESCRIPTION
**Pull request by e-Evolution**
Fixed #4021 [Bug Report] Replace obsolete library cglib.jar not compatible with JDK 11 or > 
Fixed #3973 Date changes format in records as you change Mono and Grid 
Fixed #4022 [Bug Report] Grid mode navigation has strange behavior 
Fixed #4023 [Bug Report] Quick Entry not working when the icon is pushed

### CODE REVIEW

**Comment by marcalwestf** [comment]
now starting to test....

**Comment by niclopup** [comment]
Functional Test:

Dates changing format: Tested OK

https://user-images.githubusercontent.com/31936815/206241158-6e0f7367-3f77-4d37-91d0-a3863a344951.mp4




Quick Entry: Tested OK

https://user-images.githubusercontent.com/31936815/206241127-3ec136ff-3e61-440b-81ef-412f1df69b53.mp4

File: zkwebui/WEB-INF/src/org/adempiere/webui/ZkContextProvider.java [hunk 1]
```diff
@@ -16,23 +16,45 @@
...
+					.method(any())
+					.intercept(InvocationHandlerAdapter.of(callback))
+					.make()
+					.load(ZkContextProvider.class.getClassLoader())
+					.getLoaded()).newInstance();
+		} catch (InstantiationException e) {
+			throw new RuntimeException(e);
+		} catch (IllegalAccessException e) {
+			throw new RuntimeException(e);
+		}
```
Comment (EdwinBetanc0urt) [inline zkwebui/WEB-INF/src/org/adempiere/webui/ZkContextProvider.java:55]: Is it correct to have 2 cacth for the same try statement to trigger exceptions in case of error?

**Review by EdwinBetanc0urt — CHANGES_REQUESTED** [review]

File: zkwebui/WEB-INF/src/org/adempiere/webui/ZkContextProvider.java (hunk 1 above)
Comment (e-Evolution) [reply zkwebui/WEB-INF/src/org/adempiere/webui/ZkContextProvider.java]: @EdwinBetanc0urt yes because are two possible expectations InstantiationException or IllegalAccessException , any way I change to use new syntaxis in JDK 11

**Review by marcalwestf — APPROVED** [review]
- QuickSheet
  - now it can be opened and edited
  - still not a fluid editing experience (the mouse has to be used often; whereas the intention of QuickEntry is to use only keys).
  - Nevertheless, the intention of this PR was to bring the functionality back, so the goal was reached.
- Other grid functionality: OK

Test passed.

**Comment by marcalwestf** [comment]
@e-Evolution  I will wait a while in case somebody else has the time to test.
Otherwise, I will accept these changes tomorrow at the latest.

**Comment by marcalwestf** [comment]
@EdwinBetanc0urt is this PR OK with you?

**Comment by EdwinBetanc0urt** [comment]
* Source Code Review: Ok.
* QuickEntry: Ok.
* Date Format: Ok.
* Grid Navigation: Ok.

**Review by EdwinBetanc0urt — APPROVED** [review]
